# Use Python 3.8.18 image as base
FROM python:3.8.18

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
# ADD . /app
# ADD ui.py /app/


# Install Streamlit
RUN pip install streamlit

# Expose port 8501
EXPOSE 8501

# Run the Streamlit application
CMD ["streamlit", "run", "ui.py"]
